apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: saththirdb
  name: saththirdb
  namespace: saththirns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saththirdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: saththirdb
    spec:
      volumes: # to create volume
      - name: saththirdbvol
        hostPath: # pod will take space from minion
          path: /data/saththir
          type: DirectoryOrCreate
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: saththirdb-config # name of configMap
        env: # loading other environment variables from a secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saththirdb-sec
              key: db_pass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saththirdb-sec
              key: root_pass
        resources: {}
        volumeMounts: # to mount the volume created above
        - name: saththirdbvol
          mountPath: /var/lib/mysql/
status: {}
