apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: saththirweblb
  name: saththirweblb
  namespace: saththirns
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: saththirwebapp
  type: NodePort
status:
  loadBalancer: {}
